blue-badge:
  auth-server:
    url: https://api.${bb_env}.${url}/bb_auth
    
  referencedataservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /reference-data1

logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:-DEBUG}

management:
  server:
    port: ${bb_health:-8081}

spring:
  datasource:
     ***REMOVED***
    username: ${bb_db_username:-developer}
    url: jdbc:postgresql://postgres-service.${bb_env}.${url}:5432/${bb_database:-bb_dev}?currentSchema=badgemanagement

server:
  port: ${bb_port:-8080}

amazon:
  profile: ${profile}
  s3bucket: ${bucket}
