blue-badge:
  auth-server:
    url: http://authorisation-service:8380/bb_auth
  reference-data-service:
    service-host:
      host: referencedata-service
  print-service:
    service-host:
      host: print-service

spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://postgresql:5432/bb_dev?currentSchema=badgemanagement

amazon:
  s3bucket: ${bb_badge_bucket:uk-gov-dft-ci-badge}
