blue-badge:
  auth-server:
    url: http://localhost:8380/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***
  reference-data-service:
    service-host:
      host: localhost
      port: 8580
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/reference-data-service/1.0.0
      versionaccept: application/vnd.bluebadge-api.v1+json
  print-service:
    service-host:
      host: localhost
      port: 8880
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/print-service/1.0.0
      versionaccept: application/vnd.bluebadge-api.v1+json

logging:
  level:
    root: ${APP_LOGGING_LEVEL:INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:DEBUG}

management:
  server:
    port: 8281
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  type-aliases-package: uk.gov.dft.bluebadge.service.badgemanagement.repository.domain

spring:
  datasource:
     ***REMOVED***
    username: developer
    url: jdbc:postgresql://127.0.0.1:5432/bb_dev?currentSchema=badgemanagement
  jackson:
    date-format: uk.gov.dft.bluebadge.common.api.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8280
  servlet:
    context-path: /uk-gov-dft/badge-management-service/1.0.0

springfox.documentation.swagger.v2.path: /api-docs

amazon:
  s3bucket: uk-gov-dft-dev-badge
  thumbnail-height-px: 300
  signed-url-duration-ms: 1800000
  
blacklisted.combinations: babe,c4c4,caca,d34d,dead,f3c35,f3ck,f4ck,fack,feck,‌h338,‌h35h3,‌h383,hebe,heeb,j4d3,jade,kkk  
