blue-badge:
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***
  reference-data-service:
    service-host:
      host: reference-service.${bb_env}.${url}
      port: 443
      scheme: https
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/reference-data-service/1.0.0
  print-service:
    service-host:
      host: print-service.${bb_env}.${url}
      port: 443
      scheme: https
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/print-service/1.0.0

management:
  server:
    port: ${bb_health:-8081}
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  main:
    banner-mode: "off"
  datasource:
     ***REMOVED***
    username: ${bb_db_username:-developer}
    url: jdbc:postgresql://postgres-service.${bb_env}.${url}:5432/${bb_database:-bb_dev}?currentSchema=badgemanagement

server:
  port: ${bb_port:-8080}
  servlet:
    context-path: /uk-gov-dft/badge-management-service/1.0.0

amazon:
  s3bucket: ${bb_badge_bucket}
