blue-badge:
  auth-server:
    url: https://api.${bb_env}.${url}/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***
  reference-data-service:
    service-host:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /
  print-service:
    service-host:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /

management:
  server:
    port: ${bb_health:8081}

spring:
  main:
    banner-mode: "off"
  datasource:
     ***REMOVED***
    username: ${bb_db_username}
    url: jdbc:postgresql://${RDS_HOSTNAME}:5432/${bb_database:-bb_dev}?currentSchema=badgemanagement&sslmode=verify-full

server:
  port: ${bb_port:8080}

amazon:
  s3bucket: ${bb_badge_bucket}